#Jekyll config file

# Basics
name: Dave Eargle
title: Dave Eargle
description: Information Systems Management Researcher
author: deargle
repository: 'deargle/deargle.github.io'

# Images
avatar: 'https://avatars2.githubusercontent.com/u/1174653?v=3&s=460'
gravatar_id: 

# RDFa structured data
job_title: 
employer: 
url: 'https://daveeargle.com'
location: 
  city: 'Pittsburgh'
  state: 
  country: 

# Social metadata (JSON-LD)
social:
  name: 
  links:
      
# Collections
collections:
    security_assignments:
        output: true
        permalink: /security-assignments/:path/
    security_books:
    security_films:
      
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook: 
  flickr:
  github: deargle
  instagram:
  linkedin: dave-eargle-097a2925
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: DavidEargle
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

logo: 
     
# Misc
twitter:
  username: 
google_plus_id: 
google_analytics: 'UA-35065822-1'

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js
  - assets/vendor/bootstrap-sass/stylesheets
  - assets/vendor/font-awesome/less
  - assets/vendor/font-awesome/scss
  - assets/vendor/font-awesome/src
  - assets/vendor/modernizr/feature-detects
  - assets/vendor/modernizr/media
  - assets/vendor/modernizr/test
  - assets/vendor/anchor-js/index.html
  - ".bundle"
  - vendor
  - node_modules
  - Rakefile
  
#number of items in RSS feed
rss_limit: 10

#permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

# Frontmatter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      author:
  -
    scope:
      path: ""
      type: security_assignments
    values:
      layout: tony-assignment

#disqus widget
disqus:
  shortname: 
  count: 
  api_key:

#build config
timezone: America/New_York
encoding: UTF-8
branch: master

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

sass:
  style: :compressed

# markdown: redcarpet
# redcarpet:
#   extensions:
#     - no_intra_emphasis
#     - fenced_code_blocks
#     - autolink
#     - tables
#     - strikethrough
#     - superscript
#     - with_to_data

kramdown:
 input: GFM
 hard_wrap: false

highlighter: rouge
gist:
 noscript: false
future: true

host: 0.0.0.0
