#   week:
#       class_session:
#           
#
1:
    -
        class_num: 1
        title: Introduction
        activities:
            - "<a href='https://goo.gl/forms/gVSkF51VLWYxNj9d2'>In-class survey</a>"
        date: 29-08-2017
    -  
        class_num: 2
        title: Threat Modeling
        date: 31-08-2017
        readings:
            - "<a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBl_IAKxtg8x50_hgXsJ4xBTUVDI05oLFtZGwCOg_NgpNBIBjUQiopVgD2nRWALa9ibgYNN9cQZw_d0mR4pzHe2MwAdLpDPHT4BHSsiDnouluilQIAZj8pTQ'>Secrets & Lies</a> Chapters 19 and 21"
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Threat Modeling'
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_threat_modeling/'>Lab &ndash; Threat Modeling</a>"
2:
    -
        date: 05-09-2017
        class_num: 3
        title: "Cryptography &ndash; Introduction"

        assigned_today:
            -
                name: "Install Windows lab VM if necessary"
            -
                name: "Submit screenshot of Cryptool 2.0 running on your computer"

    -
        date: 07-09-2017
        class_num: 4

        title: "Cryptography &ndash; Hashes & Symmetric"
        readings:
            - <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c05.pdf'>Anderson, Ch 5,</a> pp. 129-149
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBl_IAKxtg8x50_hgXsJ4xBTUVDI05oLFtZGwCOg_NgpNBIBjUQiopVgD2nRWALa9ibgYNN9cQZw_d0mR4pzHe2MwAdLpDPHT4BHSsiDnouluilQIAZj8pTQ'>Secrets & Lies</a> Chapters 6 & 7 (optional but highly recommended)
        due_before:
            - name: '<span class="label label-danger">Quiz:</span> Anderson, Ch. 5, pp. 129-149'
            - name: "Submit screenshot of Cryptool 2.0 running on your computer"
        assigned_today:
            - name: "<a href='/security-assignments/lab_hashing_and_symmetric_encryption/'>Lab &ndash; Symmetric</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Threat Modeling'
        
3:
    -
        date: 12-09-2017
        class_num: 5

        title: "Cryptography &ndash; Asymmetric"
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_asymmetric_encryption/'>Lab &ndash; Asymmetric</a>"
    -
        date: 13-09-2017
        due_tonight:
            -
                name: 'Email your PGP public key to Dr. Eargle (see Lab &ndash; Asymmetric)'
                
    -
        date: 14-09-2017
        class_num: 6
        title: "Cryptography &ndash; Digital Certificates and PKI"
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_digital_certificates/'>Lab &ndash; Digital Certificates</a>"
        readings:
            - "Online: Moxie Marlinspike: <a href='http://vimeo.com/32097738'>SSL And The Future Of Authenticity</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Symmetric Encryption and Hashing'
4:
    -
        date: 19-09-2017
        class_num: 7
        title: "Codes Video"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Asymmetric Encryption'
            
    -
        date: 21-09-2017
        class_num: 8
        title: Physical Security
        readings:
            - <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c11.pdf'>Anderson, Chapter 11</a>
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Anderson, Chapter 11'
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_physical_security_scavenger_hunt/'>Lab &ndash; Physical Security</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Digital Certificates'
5:
    -
        date: 26-09-2017
        class_num: 9

        title: Introduction to Computer Networking
        activities: >
            - Goal for today: setup your vms and ping them
            
            - <a href='https://docs.kali.org/general-use/kali-linux-virtual-box-guest'>Setting up a shared folder between your host and Kali</a>
            
            - <a href='https://goo.gl/forms/NAz6q5nKHNPh3i3E2'>In-class survey</a>
        readings:
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBl_IAKxtg8x50_hgXsJ4xBTUVDI05oLFtZGwCOg_NgpNBIBjUQiopVgD2nRWALa9ibgYNN9cQZw_d0mR4pzHe2MwAdLpDPHT4BHSsiDnouluilQIAZj8pTQ'>Secrets & Lies</a> Chapters 11 & 12
  
    -
        date: 28-09-2017
        class_num: 10
        title: Introduction to Linux (in-class lab)
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Physical Security'
        activities: >
            See [this page](/class/security/intro-to-linux) for the material
                
6:
    -
        date: 03-10-2017
        class_num: 11
        title: Vulnerability Scanning
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_vulnerability_scanning/'>Lab &ndash; Vulnerability Scanning</a>"
    -
        date: 05-10-2017
        class_num: 12
        title: Vulnerability Exploitation
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_exploitation/'>Lab &ndash; Exploitation</a>"
        
7:
    -
        date: 10-10-2017
        class_num: 13
        title: System Hardening

        assigned_today:
            -
                name: "<a href='/security-assignments/lab_system_hardening/'>Lab &ndash; Hardening</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Vulnerability Scanning'
    -
        date: 12-10-2017
        class_num: 14
        title: Authentication and Passwords
        readings:
            - <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c02.pdf'>Anderson, Chapter 2,</a> pp. 31-39, 56-58
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Anderson Ch. 2, pp. 31-39, 56-58'
8:
    -
        date: 17-10-2017
        class_num: 15
        title: Password Cracking
        readings:
            - Goodin, <a href='https://arstechnica.com/security/2012/08/passwords-under-assault/'>"Why passwords have never been weaker"</a>
            - 'Gosney, <a href="http://arstechnica.com/security/2016/06/how-linkedins-password-sloppiness-hurts-us-all/">How LinkedIn’s password sloppiness hurts us all</a>'
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Goodin, "Why passwords have never been weaker"'
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_password_cracking/'>Lab &ndash; Password Cracking</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Exploitation'
            - name: '<span class="label label-success">Lab:</span> Hardening'

    -
        date: 19-10-2017
        class_num: 16
        title: Midterm Prep
9:
    -
        date: 24-10-2017
        title: Midterm &ndash; no class
        assigned_today:
            -
                name: "<span class='label label-danger'><a href='/class/cu/mgmt4250/midterm/'>Midterm</a></span>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Password Cracking'
            
    -
        date: 26-10-2017
        class_num: 17
        title: Midterm &ndash; no class
        custom_css: ''
        activities: >
            - "no class today; work on midterm"

10:
    -
        class_num: 18
        title: Web application security &ndash; SQL Injection
        date: 31-10-2017
        readings:
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbQRuBDUFtVUtLYBJihhytBOGbgXtEgY7mZnqWeo7gW1EtQKdGAduuxhyw0RED0JkthhacDIrBgT4KmXlZ4HVJeQqJoAvvs4sVgL1shZTUNGBPD1iIqri5hjh76JYmw3uY8dCxj_gkC2AFa2FsCLq9QBOiLLE4G1h8AIuWkuL4shzwlGRxPMJ55sagE0GVIWphpXM8WBl0uWS8JTDdWlggVAHrmKLE3JTMdPA1HwWQUyLigf0IE_DpokoQVZB5YLh0SUVJPOiOXQtTE5Dj5LAqQlIANwWxNwphFZqDIBOuCGk0zxEVXgAYH4Xm'>Clarke, SQL Injection</a>, Chapter 1
            - <a href='www.whitehatsec.com/blog/saving-systems-from-sqli/'>Jeremiah Grossman, Saving Systems from SQLi</a>
            
        due_before:
            - name: '<span class="label label-danger">Quiz:</span> Clarke, Chapter 1'
            
        activities: >
            - "Lab &ndash; SQL Injection (in-class only)"
        
    -
        class_num: 19
        title: Web application security &ndash; XSS
        date: 02-11-2017
        readings:
            - "<a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbQRuBDUF7Gs1NjUzMmSFHK4FPG4McV84FqncsjU2A9SMHbEQE1BQ2N7fgZFAFhpACsBBRQJrDVchIBC0zUC9WAA0ogxqg3Awabq4hzh66pcnwnmW8sZkB6AiIeBQTjbkZVCBKYaVtPHgmErr8Md7EwBiYcEH7dpQhyoCVRlFibkpmOvjejgLIsQ_xQEUWRqBrEOQgqiATu3BpoPfMgc0lkG1KWBWUVJQQqQh0ZouZsRFuqxAK4KYgtkzBlYEqewMLhLewKkJ4nujgBADKlY-Z'>Stuttard and Pinto, The Web Application Hacker's Handbook</a>, Chapter 12, sections 'Varieties of XSS' and 'XSS Attacks in Action'"
        due_before:
            - name: '<span class="label label-danger">Quiz:</span> Stuttard and Pinto, Attacking Users: Cross-site Scripting, pages 431–451'
        activities: >
            - "Lab &ndash; XSS (In-class only)"
        due_tonight:
            - name: '<span class="label label-danger">Midterm due</span>'
    
    -
        title: Film "Zero Days" screening
        date: 03-11-2017
        
    
11:
                
    -
        class_num: 22
        title: Guest Speaker -- WebRoot, Dave Dufour, VP of Engineering
        date: 07-11-2017
    -
        class_num: 21
        title: Network Security Monitoring
        date: 09-11-2017
        readings:
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbUxkhpymZApsHwAYxaGc5Et8A1ATmMgJNmgHTg5kZB2xQBFjfg4604mQArTdQgO0TUshPU8iDLIpWKIbe6qaQC07yoLEvbgYNN9cQZw_d0mR4FzPe2MwAdBZEPIq5xtwMahClxdmZOTnFwIIuHtSWLTYyqTCPT8ouBt-yZ2wCOkNQBaIQVj7Hg-cuoQsm4w1NzY0swEeHykGUQSZ54wsgJ0TEG4IqXmBTCahACauCkooSZEXKMEWIjU8Is-B2Ee1NAGX0cjY'>Bejtlich, The Practice of Network Security Monitoring,</a> Chapter 1
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Bejtlich, Chapter 1'
        assigned_today:
            -
                name: "<a href='/security-assignments/lab_security_onion/'>Lab &ndash; Network Security Monitoring</a>"
        activities: >
            - [Mid-course feedback survey](https://cuboulder.qualtrics.com/jfe/form/SV_0vXfwPyM1EF60RL)
    
    
    
12:
    -
        class_num: 20
        title: Human Element
        date: 14-11-2017 
        readings:
            - <a href='https://www.ted.com/talks/bruce_schneier'>Schneier, "The Security Mirage"</a>
            -  <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c02.pdf'>Anderson, Chapter 2,</a> pp. 17-30, 40-42
            - <a href='http://www.wired.com/2012/09/cosmo-the-god-who-fell-to-earth/'>"Cosmo, the Hacker ‘God’ Who Fell to Earth," by Mat Honan</a>
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Schneier, "The Security Mirage"; Anderson, Chapter 2, pp. 17-30, 40-42; Honan, "Cosmo"'
        activities:
        assigned_today:
            - name: "<a href='/security-assignments/lab_social_engineering/'>Lab &ndash; Social Engineering (Extra credit)</a>"
        
    
    -
        class_num: 23
        title: Information Privacy
        date: 16-11-2017
        readings:
            - 'Brad Smith, <a href="https://blogs.microsoft.com/on-the-issues/2015/10/20/the-collapse-of-the-us-eu-safe-harbor-solving-the-new-privacy-rubiks-cube/">"The collapse of the US-EU Safe Harbor: Solving the new privacy Rubik''s Cube"</a>'
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> "The collapse of the US-EU Safe Harbor: Solving the new privacy Rubik''s Cube"'
        assigned_today:
            - name: "<a href='/security-assignments/lab_web_privacy_and_anonymity/'>Lab &ndash; Privacy</a>"
            - name: "<a href='/class/security/security-review/'>Threat assessment project, a.k.a 'Security Review'</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Network Security Monitoring'
        activities: >
            - Form 2-3 person teams (or you can work on your own) for the threat assessment project. Mark your teams and claim your topics [here](https://docs.google.com/spreadsheets/d/1IdYZfwJqgMWs-_gJqP-VJSB24fxVNGjHrA61ILs5x_k/edit?usp=sharing) (even if you're working on your own)
            
    -
        date: 17-11-2017
        due_tonight:
            - name: choose your teams and your topics for the threat assessment project (use the spreadsheet linked on 16 November 2017)

13:
    -
        title: Fall Break
        date: 21-11-2017
        custom_css: success

    -
        title: Fall Break
        date: 23-11-2017
        custom_css: success

14:

    -
        class_num: 24
        title: Information Security in Organizations
        date: 28-11-2017
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Privacy and Anonymity'
        
    -
        class_num: 25
        title: Security and Society
        date: 30-11-2017
        

15:
    -
        class_num: 27
        title: Presentations; USENIX Enigma talks
        due_before:
            - name: Threat assessment deliverables (document and presentation submitted to D2L) due by <b>9:00 am</b>
        date: 05-12-2017
        activities: >
            - **Room change for today only:** KOBL S125

    -
        class_num: 28
        title: No class
        custom_css: info
        date: 07-12-2017
        
16:

    -
        class_num: 26
        title: No class
        custom_css: info
        date: 12-12-2017
    
    -
        class_num: 29
        title: Course wrap-up; FCQ administration
        date: 14-12-2017
        due_before:
            - name: By 9am today, submit topics from the semester you would like to discuss in preparation for the exam <a href='https://goo.gl/forms/eHkcAt2TCf2MnDIh1'>here</a>
        activities: >
            - <a href='colorado.campuslabs.com/courseeval'>FCQ link</a>
        due_tonight:
            - name: <span class="label label-success">Lab:</span> Social Engineering (Extra credit)
            - name: '"Citizenfour" report'
            - name: '"Zero Days" report'
            - name: Book extra credit report
            - name: Movie extra credit report
        
17:
    -
        date: 18-12-2017
        title: Final exam
        custom_css: danger
        due_before:
            - name: Submit <a href='/{{ site.baseurl }}class/general/Peereval-security.docx'>this peer evaluation form</a> to D2L dropbox
        activities: > 
            - 4:30PM &ndash; 7:00PM, KOBL 302
            
            - [Final exam study guide](/class/security/final-exam-review/)

       
